name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./javascript/package-lock.json

      - run: npm ci
        working-directory: ./javascript

      - run: npm run build --if-present
        working-directory: ./javascript

      - run: npm test
        working-directory: ./javascript
        env:
          SPIDER_API_KEY: ${{ secrets.SPIDER_API_KEY }}
          SPIDER_EMAIL: ${{ secrets.SPIDER_EMAIL }}
          SPIDER_PASSWORD: ${{ secrets.SPIDER_PASSWORD }}
          SUPABASE_AUTO_REFRESH_TOKEN: "false"