name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements.txt
        working-directory: ./python

      - name: Run tests
        run: |
          pytest
        working-directory: ./python/tests
        env:
          SPIDER_API_KEY: ${{ secrets.SPIDER_API_KEY }}
          SPIDER_EMAIL: ${{ secrets.SPIDER_EMAIL }}
          SPIDER_PASSWORD: ${{ secrets.SPIDER_PASSWORD }}